[workspace]
resolver = "2"
members = [
    "mfp3000bot",
    "simple-cups",
    "simple-sane",
    "libjpeg",
    "libjpeg-sys",
]

[profile.release]
opt-level = 3
lto = "thin"
strip = "debuginfo"
panic = "abort"
