[workspace]
resolver = "2"
members = [
    "libcups-sys",
    "libcups",

    "simple-sane",
    
    "libjpeg-sys",
    "libjpeg",

    "mfp3000bot",
]

[profile.release]
opt-level = 3
lto = "thin"
strip = "debuginfo"
panic = "abort"
