mod bindings;
pub use bindings::{
    cupsAddDest, cupsAddDestMediaOptions, cupsAddIntegerOption, cupsAddOption, cupsArrayAdd,
    cupsArrayClear, cupsArrayCount, cupsArrayCurrent, cupsArrayDelete, cupsArrayDup, cupsArrayFind,
    cupsArrayFirst, cupsArrayGetIndex, cupsArrayGetInsert, cupsArrayIndex, cupsArrayInsert,
    cupsArrayLast, cupsArrayNew, cupsArrayNew2, cupsArrayNew3, cupsArrayNext, cupsArrayPrev,
    cupsArrayRemove, cupsArrayRestore, cupsArraySave, cupsArrayUserData, cupsCancelDestJob,
    cupsCancelJob, cupsCancelJob2, cupsCheckDestSupported, cupsCloseDestJob, cupsConnectDest,
    cupsCopyDest, cupsCopyDestConflicts, cupsCopyDestInfo, cupsCreateDestJob, cupsCreateJob,
    cupsDoAuthentication, cupsDoFileRequest, cupsDoIORequest, cupsDoRequest, cupsEncodeOption,
    cupsEncodeOptions, cupsEncodeOptions2, cupsEncryption, cupsEnumDests, cupsFileClose,
    cupsFileCompression, cupsFileEOF, cupsFileFind, cupsFileFlush, cupsFileGetChar,
    cupsFileGetConf, cupsFileGetLine, cupsFileGets, cupsFileLock, cupsFileNumber, cupsFileOpen,
    cupsFileOpenFd, cupsFilePeekChar, cupsFilePrintf, cupsFilePutChar, cupsFilePutConf,
    cupsFilePuts, cupsFileRead, cupsFileRewind, cupsFileSeek, cupsFileStderr, cupsFileStdin,
    cupsFileStdout, cupsFileTell, cupsFileUnlock, cupsFileWrite, cupsFindDestDefault,
    cupsFindDestReady, cupsFindDestSupported, cupsFinishDestDocument, cupsFinishDocument,
    cupsFreeDestInfo, cupsFreeDests, cupsFreeJobs, cupsFreeOptions, cupsGetClasses, cupsGetDefault,
    cupsGetDefault2, cupsGetDest, cupsGetDestMediaByIndex, cupsGetDestMediaByName,
    cupsGetDestMediaBySize, cupsGetDestMediaCount, cupsGetDestMediaDefault, cupsGetDestWithURI,
    cupsGetDests, cupsGetDests2, cupsGetFd, cupsGetFile, cupsGetIntegerOption, cupsGetJobs,
    cupsGetJobs2, cupsGetNamedDest, cupsGetOption, cupsGetPassword, cupsGetPassword2,
    cupsGetPrinters, cupsGetResponse, cupsHashData, cupsHashString, cupsLangDefault,
    cupsLangEncoding, cupsLangFlush, cupsLangFree, cupsLangGet, cupsLastError, cupsLastErrorString,
    cupsLocalizeDestMedia, cupsLocalizeDestOption, cupsLocalizeDestValue,
    cupsMakeServerCredentials, cupsNotifySubject, cupsNotifyText, cupsParseOptions, cupsPrintFile,
    cupsPrintFile2, cupsPrintFiles, cupsPrintFiles2, cupsPutFd, cupsPutFile, cupsReadResponseData,
    cupsRemoveDest, cupsRemoveOption, cupsSendRequest, cupsServer, cupsSetClientCertCB,
    cupsSetCredentials, cupsSetDefaultDest, cupsSetDests, cupsSetDests2, cupsSetEncryption,
    cupsSetPasswordCB, cupsSetPasswordCB2, cupsSetServer, cupsSetServerCertCB,
    cupsSetServerCredentials, cupsSetUser, cupsSetUserAgent, cupsStartDestDocument,
    cupsStartDocument, cupsTempFd, cupsTempFile, cupsTempFile2, cupsUser, cupsUserAgent,
    cupsWriteRequestData, cups_acopy_func_t, cups_afree_func_t, cups_ahash_func_t,
    cups_array_func_t, cups_array_t, cups_client_cert_cb_t, cups_dest_cb_t, cups_dest_t,
    cups_dinfo_t, cups_encoding_e, cups_encoding_e_CUPS_AUTO_ENCODING,
    cups_encoding_e_CUPS_ENCODING_DBCS_END, cups_encoding_e_CUPS_ENCODING_SBCS_END,
    cups_encoding_e_CUPS_ENCODING_VBCS_END, cups_encoding_e_CUPS_EUC_CN,
    cups_encoding_e_CUPS_EUC_JP, cups_encoding_e_CUPS_EUC_KR, cups_encoding_e_CUPS_EUC_TW,
    cups_encoding_e_CUPS_ISO8859_1, cups_encoding_e_CUPS_ISO8859_10,
    cups_encoding_e_CUPS_ISO8859_11, cups_encoding_e_CUPS_ISO8859_13,
    cups_encoding_e_CUPS_ISO8859_14, cups_encoding_e_CUPS_ISO8859_15,
    cups_encoding_e_CUPS_ISO8859_16, cups_encoding_e_CUPS_ISO8859_2,
    cups_encoding_e_CUPS_ISO8859_3, cups_encoding_e_CUPS_ISO8859_4, cups_encoding_e_CUPS_ISO8859_5,
    cups_encoding_e_CUPS_ISO8859_6, cups_encoding_e_CUPS_ISO8859_7, cups_encoding_e_CUPS_ISO8859_8,
    cups_encoding_e_CUPS_ISO8859_9, cups_encoding_e_CUPS_JIS_X0213, cups_encoding_e_CUPS_KOI8_R,
    cups_encoding_e_CUPS_KOI8_U, cups_encoding_e_CUPS_MAC_ROMAN, cups_encoding_e_CUPS_US_ASCII,
    cups_encoding_e_CUPS_UTF8, cups_encoding_e_CUPS_WINDOWS_1250,
    cups_encoding_e_CUPS_WINDOWS_1251, cups_encoding_e_CUPS_WINDOWS_1252,
    cups_encoding_e_CUPS_WINDOWS_1253, cups_encoding_e_CUPS_WINDOWS_1254,
    cups_encoding_e_CUPS_WINDOWS_1255, cups_encoding_e_CUPS_WINDOWS_1256,
    cups_encoding_e_CUPS_WINDOWS_1257, cups_encoding_e_CUPS_WINDOWS_1258,
    cups_encoding_e_CUPS_WINDOWS_1361, cups_encoding_e_CUPS_WINDOWS_874,
    cups_encoding_e_CUPS_WINDOWS_932, cups_encoding_e_CUPS_WINDOWS_936,
    cups_encoding_e_CUPS_WINDOWS_949, cups_encoding_e_CUPS_WINDOWS_950, cups_encoding_t,
    cups_file_t, cups_job_t, cups_lang_t, cups_option_t, cups_password_cb2_t, cups_password_cb_t,
    cups_ptype_e, cups_ptype_e_CUPS_PRINTER_3D, cups_ptype_e_CUPS_PRINTER_AUTHENTICATED,
    cups_ptype_e_CUPS_PRINTER_BIND, cups_ptype_e_CUPS_PRINTER_BW, cups_ptype_e_CUPS_PRINTER_CLASS,
    cups_ptype_e_CUPS_PRINTER_COLLATE, cups_ptype_e_CUPS_PRINTER_COLOR,
    cups_ptype_e_CUPS_PRINTER_COMMANDS, cups_ptype_e_CUPS_PRINTER_COPIES,
    cups_ptype_e_CUPS_PRINTER_COVER, cups_ptype_e_CUPS_PRINTER_DEFAULT,
    cups_ptype_e_CUPS_PRINTER_DELETE, cups_ptype_e_CUPS_PRINTER_DISCOVERED,
    cups_ptype_e_CUPS_PRINTER_DUPLEX, cups_ptype_e_CUPS_PRINTER_FAX,
    cups_ptype_e_CUPS_PRINTER_IMPLICIT, cups_ptype_e_CUPS_PRINTER_LARGE,
    cups_ptype_e_CUPS_PRINTER_LOCAL, cups_ptype_e_CUPS_PRINTER_MEDIUM,
    cups_ptype_e_CUPS_PRINTER_MFP, cups_ptype_e_CUPS_PRINTER_NOT_SHARED,
    cups_ptype_e_CUPS_PRINTER_OPTIONS, cups_ptype_e_CUPS_PRINTER_PUNCH,
    cups_ptype_e_CUPS_PRINTER_REJECTING, cups_ptype_e_CUPS_PRINTER_REMOTE,
    cups_ptype_e_CUPS_PRINTER_SCANNER, cups_ptype_e_CUPS_PRINTER_SMALL,
    cups_ptype_e_CUPS_PRINTER_SORT, cups_ptype_e_CUPS_PRINTER_STAPLE,
    cups_ptype_e_CUPS_PRINTER_VARIABLE, cups_ptype_t, httpAcceptConnection, httpAddCredential,
    httpAddrAny, httpAddrClose, httpAddrConnect, httpAddrConnect2, httpAddrCopyList, httpAddrEqual,
    httpAddrFamily, httpAddrFreeList, httpAddrGetList, httpAddrLength, httpAddrListen,
    httpAddrLocalhost, httpAddrLookup, httpAddrPort, httpAddrString, httpAssembleURI,
    httpAssembleURIf, httpAssembleUUID, httpBlocking, httpCheck, httpClearCookie, httpClearFields,
    httpClose, httpCompareCredentials, httpConnect, httpConnect2, httpConnectEncrypt,
    httpCopyCredentials, httpCredentialsAreValidForName, httpCredentialsGetExpiration,
    httpCredentialsGetTrust, httpCredentialsString, httpDecode64, httpDecode64_2, httpDelete,
    httpEncode64, httpEncode64_2, httpEncryption, httpError, httpFieldValue, httpFlush,
    httpFlushWrite, httpFreeCredentials, httpGet, httpGetActivity, httpGetAddress,
    httpGetAuthString, httpGetBlocking, httpGetContentEncoding, httpGetCookie, httpGetDateString,
    httpGetDateString2, httpGetDateTime, httpGetEncryption, httpGetExpect, httpGetFd, httpGetField,
    httpGetHostByName, httpGetHostname, httpGetKeepAlive, httpGetLength, httpGetLength2,
    httpGetPending, httpGetReady, httpGetRemaining, httpGetState, httpGetStatus, httpGetSubField,
    httpGetSubField2, httpGetVersion, httpGets, httpHead, httpInitialize, httpIsChunked,
    httpIsEncrypted, httpLoadCredentials, httpMD5, httpMD5Final, httpMD5String, httpOptions,
    httpPeek, httpPost, httpPrintf, httpPut, httpRead, httpRead2, httpReadRequest, httpReconnect,
    httpReconnect2, httpResolveHostname, httpSaveCredentials, httpSeparate, httpSeparate2,
    httpSeparateURI, httpSetAuthString, httpSetCookie, httpSetCredentials, httpSetDefaultField,
    httpSetExpect, httpSetField, httpSetKeepAlive, httpSetLength, httpSetTimeout, httpShutdown,
    httpStateString, httpStatus, httpTrace, httpURIStatusString, httpUpdate, httpWait, httpWrite,
    httpWrite2, httpWriteResponse, http_addr_t, http_addrlist_t, http_auth_e,
    http_auth_e_HTTP_AUTH_BASIC, http_auth_e_HTTP_AUTH_MD5, http_auth_e_HTTP_AUTH_MD5_INT,
    http_auth_e_HTTP_AUTH_MD5_SESS, http_auth_e_HTTP_AUTH_MD5_SESS_INT,
    http_auth_e_HTTP_AUTH_NEGOTIATE, http_auth_e_HTTP_AUTH_NONE, http_auth_t, http_credential_t,
    http_encoding_e, http_encoding_e_HTTP_ENCODING_CHUNKED, http_encoding_e_HTTP_ENCODING_FIELDS,
    http_encoding_e_HTTP_ENCODING_LENGTH, http_encoding_t, http_encryption_e,
    http_encryption_e_HTTP_ENCRYPTION_ALWAYS, http_encryption_e_HTTP_ENCRYPTION_IF_REQUESTED,
    http_encryption_e_HTTP_ENCRYPTION_NEVER, http_encryption_e_HTTP_ENCRYPTION_REQUIRED,
    http_encryption_t, http_field_e, http_field_e_HTTP_FIELD_ACCEPT_ENCODING,
    http_field_e_HTTP_FIELD_ACCEPT_LANGUAGE, http_field_e_HTTP_FIELD_ACCEPT_RANGES,
    http_field_e_HTTP_FIELD_ALLOW, http_field_e_HTTP_FIELD_AUTHENTICATION_INFO,
    http_field_e_HTTP_FIELD_AUTHORIZATION, http_field_e_HTTP_FIELD_CONNECTION,
    http_field_e_HTTP_FIELD_CONTENT_ENCODING, http_field_e_HTTP_FIELD_CONTENT_LANGUAGE,
    http_field_e_HTTP_FIELD_CONTENT_LENGTH, http_field_e_HTTP_FIELD_CONTENT_LOCATION,
    http_field_e_HTTP_FIELD_CONTENT_MD5, http_field_e_HTTP_FIELD_CONTENT_RANGE,
    http_field_e_HTTP_FIELD_CONTENT_TYPE, http_field_e_HTTP_FIELD_CONTENT_VERSION,
    http_field_e_HTTP_FIELD_DATE, http_field_e_HTTP_FIELD_HOST,
    http_field_e_HTTP_FIELD_IF_MODIFIED_SINCE, http_field_e_HTTP_FIELD_IF_UNMODIFIED_SINCE,
    http_field_e_HTTP_FIELD_KEEP_ALIVE, http_field_e_HTTP_FIELD_LAST_MODIFIED,
    http_field_e_HTTP_FIELD_LINK, http_field_e_HTTP_FIELD_LOCATION, http_field_e_HTTP_FIELD_MAX,
    http_field_e_HTTP_FIELD_RANGE, http_field_e_HTTP_FIELD_REFERER,
    http_field_e_HTTP_FIELD_RETRY_AFTER, http_field_e_HTTP_FIELD_SERVER,
    http_field_e_HTTP_FIELD_TRANSFER_ENCODING, http_field_e_HTTP_FIELD_UNKNOWN,
    http_field_e_HTTP_FIELD_UPGRADE, http_field_e_HTTP_FIELD_USER_AGENT,
    http_field_e_HTTP_FIELD_WWW_AUTHENTICATE, http_field_t, http_keepalive_e_HTTP_KEEPALIVE_OFF,
    http_keepalive_e_HTTP_KEEPALIVE_ON, http_keepalive_t, http_state_e,
    http_state_e_HTTP_STATE_CONNECT, http_state_e_HTTP_STATE_DELETE, http_state_e_HTTP_STATE_ERROR,
    http_state_e_HTTP_STATE_GET, http_state_e_HTTP_STATE_GET_SEND, http_state_e_HTTP_STATE_HEAD,
    http_state_e_HTTP_STATE_OPTIONS, http_state_e_HTTP_STATE_POST,
    http_state_e_HTTP_STATE_POST_RECV, http_state_e_HTTP_STATE_POST_SEND,
    http_state_e_HTTP_STATE_PUT, http_state_e_HTTP_STATE_PUT_RECV, http_state_e_HTTP_STATE_STATUS,
    http_state_e_HTTP_STATE_TRACE, http_state_e_HTTP_STATE_UNKNOWN_METHOD,
    http_state_e_HTTP_STATE_UNKNOWN_VERSION, http_state_e_HTTP_STATE_WAITING, http_state_t,
    http_status_e, http_status_e_HTTP_STATUS_ACCEPTED, http_status_e_HTTP_STATUS_BAD_GATEWAY,
    http_status_e_HTTP_STATUS_BAD_REQUEST, http_status_e_HTTP_STATUS_CONFLICT,
    http_status_e_HTTP_STATUS_CONTINUE, http_status_e_HTTP_STATUS_CREATED,
    http_status_e_HTTP_STATUS_CUPS_AUTHORIZATION_CANCELED,
    http_status_e_HTTP_STATUS_CUPS_PKI_ERROR, http_status_e_HTTP_STATUS_CUPS_WEBIF_DISABLED,
    http_status_e_HTTP_STATUS_ERROR, http_status_e_HTTP_STATUS_EXPECTATION_FAILED,
    http_status_e_HTTP_STATUS_FORBIDDEN, http_status_e_HTTP_STATUS_FOUND,
    http_status_e_HTTP_STATUS_GATEWAY_TIMEOUT, http_status_e_HTTP_STATUS_GONE,
    http_status_e_HTTP_STATUS_LENGTH_REQUIRED, http_status_e_HTTP_STATUS_METHOD_NOT_ALLOWED,
    http_status_e_HTTP_STATUS_MOVED_PERMANENTLY, http_status_e_HTTP_STATUS_MULTIPLE_CHOICES,
    http_status_e_HTTP_STATUS_NONE, http_status_e_HTTP_STATUS_NOT_ACCEPTABLE,
    http_status_e_HTTP_STATUS_NOT_AUTHORITATIVE, http_status_e_HTTP_STATUS_NOT_FOUND,
    http_status_e_HTTP_STATUS_NOT_IMPLEMENTED, http_status_e_HTTP_STATUS_NOT_MODIFIED,
    http_status_e_HTTP_STATUS_NOT_SUPPORTED, http_status_e_HTTP_STATUS_NO_CONTENT,
    http_status_e_HTTP_STATUS_OK, http_status_e_HTTP_STATUS_PARTIAL_CONTENT,
    http_status_e_HTTP_STATUS_PAYMENT_REQUIRED, http_status_e_HTTP_STATUS_PRECONDITION,
    http_status_e_HTTP_STATUS_PROXY_AUTHENTICATION, http_status_e_HTTP_STATUS_REQUESTED_RANGE,
    http_status_e_HTTP_STATUS_REQUEST_TIMEOUT, http_status_e_HTTP_STATUS_REQUEST_TOO_LARGE,
    http_status_e_HTTP_STATUS_RESET_CONTENT, http_status_e_HTTP_STATUS_SEE_OTHER,
    http_status_e_HTTP_STATUS_SERVER_ERROR, http_status_e_HTTP_STATUS_SERVICE_UNAVAILABLE,
    http_status_e_HTTP_STATUS_SWITCHING_PROTOCOLS, http_status_e_HTTP_STATUS_TEMPORARY_REDIRECT,
    http_status_e_HTTP_STATUS_UNAUTHORIZED, http_status_e_HTTP_STATUS_UNSUPPORTED_MEDIATYPE,
    http_status_e_HTTP_STATUS_UPGRADE_REQUIRED, http_status_e_HTTP_STATUS_URI_TOO_LONG,
    http_status_e_HTTP_STATUS_USE_PROXY, http_status_t, http_t, http_timeout_cb_t, http_trust_e,
    http_trust_e_HTTP_TRUST_CHANGED, http_trust_e_HTTP_TRUST_EXPIRED,
    http_trust_e_HTTP_TRUST_INVALID, http_trust_e_HTTP_TRUST_OK, http_trust_e_HTTP_TRUST_RENEWED,
    http_trust_e_HTTP_TRUST_UNKNOWN, http_trust_t, http_uri_coding_e,
    http_uri_coding_e_HTTP_URI_CODING_ALL, http_uri_coding_e_HTTP_URI_CODING_HOSTNAME,
    http_uri_coding_e_HTTP_URI_CODING_MOST, http_uri_coding_e_HTTP_URI_CODING_NONE,
    http_uri_coding_e_HTTP_URI_CODING_QUERY, http_uri_coding_e_HTTP_URI_CODING_RESOURCE,
    http_uri_coding_e_HTTP_URI_CODING_RFC6874, http_uri_coding_e_HTTP_URI_CODING_USERNAME,
    http_uri_coding_t, http_uri_status_e, http_uri_status_e_HTTP_URI_STATUS_BAD_ARGUMENTS,
    http_uri_status_e_HTTP_URI_STATUS_BAD_HOSTNAME, http_uri_status_e_HTTP_URI_STATUS_BAD_PORT,
    http_uri_status_e_HTTP_URI_STATUS_BAD_RESOURCE, http_uri_status_e_HTTP_URI_STATUS_BAD_SCHEME,
    http_uri_status_e_HTTP_URI_STATUS_BAD_URI, http_uri_status_e_HTTP_URI_STATUS_BAD_USERNAME,
    http_uri_status_e_HTTP_URI_STATUS_MISSING_RESOURCE,
    http_uri_status_e_HTTP_URI_STATUS_MISSING_SCHEME, http_uri_status_e_HTTP_URI_STATUS_OK,
    http_uri_status_e_HTTP_URI_STATUS_OVERFLOW, http_uri_status_e_HTTP_URI_STATUS_UNKNOWN_SCHEME,
    http_uri_status_t, http_version_e, http_version_e_HTTP_VERSION_0_9,
    http_version_e_HTTP_VERSION_1_0, http_version_e_HTTP_VERSION_1_1, http_version_t,
    ippAddBoolean, ippAddBooleans, ippAddCollection, ippAddCollections, ippAddDate, ippAddInteger,
    ippAddIntegers, ippAddOctetString, ippAddOutOfBand, ippAddRange, ippAddRanges,
    ippAddResolution, ippAddResolutions, ippAddSeparator, ippAddString, ippAddStringf,
    ippAddStringfv, ippAddStrings, ippAttributeString, ippContainsInteger, ippContainsString,
    ippCopyAttribute, ippCopyAttributes, ippCreateRequestedArray, ippDateToTime, ippDelete,
    ippDeleteAttribute, ippDeleteValues, ippEnumString, ippEnumValue, ippErrorString,
    ippErrorValue, ippFindAttribute, ippFindNextAttribute, ippFirstAttribute, ippGetBoolean,
    ippGetCollection, ippGetCount, ippGetDate, ippGetGroupTag, ippGetInteger, ippGetName,
    ippGetOctetString, ippGetOperation, ippGetRange, ippGetRequestId, ippGetResolution,
    ippGetState, ippGetStatusCode, ippGetString, ippGetValueTag, ippGetVersion, ippLength, ippNew,
    ippNewRequest, ippNewResponse, ippNextAttribute, ippOpString, ippOpValue, ippPort, ippRead,
    ippReadFile, ippReadIO, ippSetBoolean, ippSetCollection, ippSetDate, ippSetGroupTag,
    ippSetInteger, ippSetName, ippSetOctetString, ippSetOperation, ippSetPort, ippSetRange,
    ippSetRequestId, ippSetResolution, ippSetState, ippSetStatusCode, ippSetString, ippSetStringf,
    ippSetStringfv, ippSetValueTag, ippSetVersion, ippStateString, ippTagString, ippTagValue,
    ippTimeToDate, ippValidateAttribute, ippValidateAttributes, ippWrite, ippWriteFile, ippWriteIO,
    ipp_attribute_t, ipp_copycb_t, ipp_dstate_e, ipp_dstate_e_IPP_DSTATE_ABORTED,
    ipp_dstate_e_IPP_DSTATE_CANCELED, ipp_dstate_e_IPP_DSTATE_COMPLETED,
    ipp_dstate_e_IPP_DSTATE_PENDING, ipp_dstate_e_IPP_DSTATE_PROCESSING, ipp_dstate_t,
    ipp_finish_t, ipp_finishings_e, ipp_finishings_e_IPP_FINISHINGS_BALE,
    ipp_finishings_e_IPP_FINISHINGS_BIND, ipp_finishings_e_IPP_FINISHINGS_BIND_BOTTOM,
    ipp_finishings_e_IPP_FINISHINGS_BIND_LEFT, ipp_finishings_e_IPP_FINISHINGS_BIND_RIGHT,
    ipp_finishings_e_IPP_FINISHINGS_BIND_TOP, ipp_finishings_e_IPP_FINISHINGS_BOOKLET_MAKER,
    ipp_finishings_e_IPP_FINISHINGS_COAT, ipp_finishings_e_IPP_FINISHINGS_COVER,
    ipp_finishings_e_IPP_FINISHINGS_CUPS_FOLD_ACCORDION,
    ipp_finishings_e_IPP_FINISHINGS_CUPS_FOLD_DOUBLE_GATE,
    ipp_finishings_e_IPP_FINISHINGS_CUPS_FOLD_GATE, ipp_finishings_e_IPP_FINISHINGS_CUPS_FOLD_HALF,
    ipp_finishings_e_IPP_FINISHINGS_CUPS_FOLD_HALF_Z,
    ipp_finishings_e_IPP_FINISHINGS_CUPS_FOLD_LEFT_GATE,
    ipp_finishings_e_IPP_FINISHINGS_CUPS_FOLD_LETTER,
    ipp_finishings_e_IPP_FINISHINGS_CUPS_FOLD_PARALLEL,
    ipp_finishings_e_IPP_FINISHINGS_CUPS_FOLD_POSTER,
    ipp_finishings_e_IPP_FINISHINGS_CUPS_FOLD_RIGHT_GATE,
    ipp_finishings_e_IPP_FINISHINGS_CUPS_FOLD_Z,
    ipp_finishings_e_IPP_FINISHINGS_CUPS_PUNCH_BOTTOM_LEFT,
    ipp_finishings_e_IPP_FINISHINGS_CUPS_PUNCH_BOTTOM_RIGHT,
    ipp_finishings_e_IPP_FINISHINGS_CUPS_PUNCH_DUAL_BOTTOM,
    ipp_finishings_e_IPP_FINISHINGS_CUPS_PUNCH_DUAL_LEFT,
    ipp_finishings_e_IPP_FINISHINGS_CUPS_PUNCH_DUAL_RIGHT,
    ipp_finishings_e_IPP_FINISHINGS_CUPS_PUNCH_DUAL_TOP,
    ipp_finishings_e_IPP_FINISHINGS_CUPS_PUNCH_QUAD_BOTTOM,
    ipp_finishings_e_IPP_FINISHINGS_CUPS_PUNCH_QUAD_LEFT,
    ipp_finishings_e_IPP_FINISHINGS_CUPS_PUNCH_QUAD_RIGHT,
    ipp_finishings_e_IPP_FINISHINGS_CUPS_PUNCH_QUAD_TOP,
    ipp_finishings_e_IPP_FINISHINGS_CUPS_PUNCH_TOP_LEFT,
    ipp_finishings_e_IPP_FINISHINGS_CUPS_PUNCH_TOP_RIGHT,
    ipp_finishings_e_IPP_FINISHINGS_CUPS_PUNCH_TRIPLE_BOTTOM,
    ipp_finishings_e_IPP_FINISHINGS_CUPS_PUNCH_TRIPLE_LEFT,
    ipp_finishings_e_IPP_FINISHINGS_CUPS_PUNCH_TRIPLE_RIGHT,
    ipp_finishings_e_IPP_FINISHINGS_CUPS_PUNCH_TRIPLE_TOP,
    ipp_finishings_e_IPP_FINISHINGS_EDGE_STITCH,
    ipp_finishings_e_IPP_FINISHINGS_EDGE_STITCH_BOTTOM,
    ipp_finishings_e_IPP_FINISHINGS_EDGE_STITCH_LEFT,
    ipp_finishings_e_IPP_FINISHINGS_EDGE_STITCH_RIGHT,
    ipp_finishings_e_IPP_FINISHINGS_EDGE_STITCH_TOP, ipp_finishings_e_IPP_FINISHINGS_FOLD,
    ipp_finishings_e_IPP_FINISHINGS_FOLD_ACCORDION,
    ipp_finishings_e_IPP_FINISHINGS_FOLD_DOUBLE_GATE,
    ipp_finishings_e_IPP_FINISHINGS_FOLD_ENGINEERING_Z, ipp_finishings_e_IPP_FINISHINGS_FOLD_GATE,
    ipp_finishings_e_IPP_FINISHINGS_FOLD_HALF, ipp_finishings_e_IPP_FINISHINGS_FOLD_HALF_Z,
    ipp_finishings_e_IPP_FINISHINGS_FOLD_LEFT_GATE, ipp_finishings_e_IPP_FINISHINGS_FOLD_LETTER,
    ipp_finishings_e_IPP_FINISHINGS_FOLD_PARALLEL, ipp_finishings_e_IPP_FINISHINGS_FOLD_POSTER,
    ipp_finishings_e_IPP_FINISHINGS_FOLD_RIGHT_GATE, ipp_finishings_e_IPP_FINISHINGS_FOLD_Z,
    ipp_finishings_e_IPP_FINISHINGS_JOG_OFFSET, ipp_finishings_e_IPP_FINISHINGS_LAMINATE,
    ipp_finishings_e_IPP_FINISHINGS_NONE, ipp_finishings_e_IPP_FINISHINGS_PUNCH,
    ipp_finishings_e_IPP_FINISHINGS_PUNCH_BOTTOM_LEFT,
    ipp_finishings_e_IPP_FINISHINGS_PUNCH_BOTTOM_RIGHT,
    ipp_finishings_e_IPP_FINISHINGS_PUNCH_DUAL_BOTTOM,
    ipp_finishings_e_IPP_FINISHINGS_PUNCH_DUAL_LEFT,
    ipp_finishings_e_IPP_FINISHINGS_PUNCH_DUAL_RIGHT,
    ipp_finishings_e_IPP_FINISHINGS_PUNCH_DUAL_TOP,
    ipp_finishings_e_IPP_FINISHINGS_PUNCH_MULTIPLE_BOTTOM,
    ipp_finishings_e_IPP_FINISHINGS_PUNCH_MULTIPLE_LEFT,
    ipp_finishings_e_IPP_FINISHINGS_PUNCH_MULTIPLE_RIGHT,
    ipp_finishings_e_IPP_FINISHINGS_PUNCH_MULTIPLE_TOP,
    ipp_finishings_e_IPP_FINISHINGS_PUNCH_QUAD_BOTTOM,
    ipp_finishings_e_IPP_FINISHINGS_PUNCH_QUAD_LEFT,
    ipp_finishings_e_IPP_FINISHINGS_PUNCH_QUAD_RIGHT,
    ipp_finishings_e_IPP_FINISHINGS_PUNCH_QUAD_TOP, ipp_finishings_e_IPP_FINISHINGS_PUNCH_TOP_LEFT,
    ipp_finishings_e_IPP_FINISHINGS_PUNCH_TOP_RIGHT,
    ipp_finishings_e_IPP_FINISHINGS_PUNCH_TRIPLE_BOTTOM,
    ipp_finishings_e_IPP_FINISHINGS_PUNCH_TRIPLE_LEFT,
    ipp_finishings_e_IPP_FINISHINGS_PUNCH_TRIPLE_RIGHT,
    ipp_finishings_e_IPP_FINISHINGS_PUNCH_TRIPLE_TOP,
    ipp_finishings_e_IPP_FINISHINGS_SADDLE_STITCH, ipp_finishings_e_IPP_FINISHINGS_STAPLE,
    ipp_finishings_e_IPP_FINISHINGS_STAPLE_BOTTOM_LEFT,
    ipp_finishings_e_IPP_FINISHINGS_STAPLE_BOTTOM_RIGHT,
    ipp_finishings_e_IPP_FINISHINGS_STAPLE_DUAL_BOTTOM,
    ipp_finishings_e_IPP_FINISHINGS_STAPLE_DUAL_LEFT,
    ipp_finishings_e_IPP_FINISHINGS_STAPLE_DUAL_RIGHT,
    ipp_finishings_e_IPP_FINISHINGS_STAPLE_DUAL_TOP,
    ipp_finishings_e_IPP_FINISHINGS_STAPLE_TOP_LEFT,
    ipp_finishings_e_IPP_FINISHINGS_STAPLE_TOP_RIGHT,
    ipp_finishings_e_IPP_FINISHINGS_STAPLE_TRIPLE_BOTTOM,
    ipp_finishings_e_IPP_FINISHINGS_STAPLE_TRIPLE_LEFT,
    ipp_finishings_e_IPP_FINISHINGS_STAPLE_TRIPLE_RIGHT,
    ipp_finishings_e_IPP_FINISHINGS_STAPLE_TRIPLE_TOP, ipp_finishings_e_IPP_FINISHINGS_TRIM,
    ipp_finishings_e_IPP_FINISHINGS_TRIM_AFTER_COPIES,
    ipp_finishings_e_IPP_FINISHINGS_TRIM_AFTER_DOCUMENTS,
    ipp_finishings_e_IPP_FINISHINGS_TRIM_AFTER_JOB,
    ipp_finishings_e_IPP_FINISHINGS_TRIM_AFTER_PAGES, ipp_finishings_t, ipp_iocb_t, ipp_jcollate_e,
    ipp_jcollate_e_IPP_JCOLLATE_COLLATED_DOCUMENTS,
    ipp_jcollate_e_IPP_JCOLLATE_UNCOLLATED_DOCUMENTS,
    ipp_jcollate_e_IPP_JCOLLATE_UNCOLLATED_SHEETS, ipp_jcollate_t, ipp_jstate_e,
    ipp_jstate_e_IPP_JSTATE_ABORTED, ipp_jstate_e_IPP_JSTATE_CANCELED,
    ipp_jstate_e_IPP_JSTATE_COMPLETED, ipp_jstate_e_IPP_JSTATE_HELD,
    ipp_jstate_e_IPP_JSTATE_PENDING, ipp_jstate_e_IPP_JSTATE_PROCESSING,
    ipp_jstate_e_IPP_JSTATE_STOPPED, ipp_jstate_t, ipp_op_e, ipp_op_e_IPP_OP_ACKNOWLEDGE_DOCUMENT,
    ipp_op_e_IPP_OP_ACKNOWLEDGE_IDENTIFY_PRINTER, ipp_op_e_IPP_OP_ACKNOWLEDGE_JOB,
    ipp_op_e_IPP_OP_ACTIVATE_PRINTER, ipp_op_e_IPP_OP_ADD_DOCUMENT_IMAGES,
    ipp_op_e_IPP_OP_ALLOCATE_PRINTER_RESOURCES, ipp_op_e_IPP_OP_CANCEL_CURRENT_JOB,
    ipp_op_e_IPP_OP_CANCEL_DOCUMENT, ipp_op_e_IPP_OP_CANCEL_JOB, ipp_op_e_IPP_OP_CANCEL_JOBS,
    ipp_op_e_IPP_OP_CANCEL_MY_JOBS, ipp_op_e_IPP_OP_CANCEL_RESOURCE,
    ipp_op_e_IPP_OP_CANCEL_SUBSCRIPTION, ipp_op_e_IPP_OP_CLOSE_JOB, ipp_op_e_IPP_OP_CREATE_JOB,
    ipp_op_e_IPP_OP_CREATE_JOB_SUBSCRIPTIONS, ipp_op_e_IPP_OP_CREATE_PRINTER,
    ipp_op_e_IPP_OP_CREATE_PRINTER_SUBSCRIPTIONS, ipp_op_e_IPP_OP_CREATE_RESOURCE,
    ipp_op_e_IPP_OP_CREATE_RESOURCE_SUBSCRIPTIONS, ipp_op_e_IPP_OP_CREATE_SYSTEM_SUBSCRIPTIONS,
    ipp_op_e_IPP_OP_CUPS_ACCEPT_JOBS, ipp_op_e_IPP_OP_CUPS_ADD_MODIFY_CLASS,
    ipp_op_e_IPP_OP_CUPS_ADD_MODIFY_PRINTER, ipp_op_e_IPP_OP_CUPS_AUTHENTICATE_JOB,
    ipp_op_e_IPP_OP_CUPS_CREATE_LOCAL_PRINTER, ipp_op_e_IPP_OP_CUPS_DELETE_CLASS,
    ipp_op_e_IPP_OP_CUPS_DELETE_PRINTER, ipp_op_e_IPP_OP_CUPS_GET_CLASSES,
    ipp_op_e_IPP_OP_CUPS_GET_DEFAULT, ipp_op_e_IPP_OP_CUPS_GET_DEVICES,
    ipp_op_e_IPP_OP_CUPS_GET_DOCUMENT, ipp_op_e_IPP_OP_CUPS_GET_PPD, ipp_op_e_IPP_OP_CUPS_GET_PPDS,
    ipp_op_e_IPP_OP_CUPS_GET_PRINTERS, ipp_op_e_IPP_OP_CUPS_INVALID, ipp_op_e_IPP_OP_CUPS_MOVE_JOB,
    ipp_op_e_IPP_OP_CUPS_NONE, ipp_op_e_IPP_OP_CUPS_REJECT_JOBS, ipp_op_e_IPP_OP_CUPS_SET_DEFAULT,
    ipp_op_e_IPP_OP_DEACTIVATE_PRINTER, ipp_op_e_IPP_OP_DEALLOCATE_PRINTER_RESOURCES,
    ipp_op_e_IPP_OP_DELETE_DOCUMENT, ipp_op_e_IPP_OP_DELETE_PRINTER,
    ipp_op_e_IPP_OP_DEREGISTER_OUTPUT_DEVICE, ipp_op_e_IPP_OP_DISABLE_ALL_PRINTERS,
    ipp_op_e_IPP_OP_DISABLE_PRINTER, ipp_op_e_IPP_OP_ENABLE_ALL_PRINTERS,
    ipp_op_e_IPP_OP_ENABLE_PRINTER, ipp_op_e_IPP_OP_FETCH_DOCUMENT, ipp_op_e_IPP_OP_FETCH_JOB,
    ipp_op_e_IPP_OP_GET_DOCUMENTS, ipp_op_e_IPP_OP_GET_DOCUMENT_ATTRIBUTES,
    ipp_op_e_IPP_OP_GET_JOBS, ipp_op_e_IPP_OP_GET_JOB_ATTRIBUTES,
    ipp_op_e_IPP_OP_GET_NEXT_DOCUMENT_DATA, ipp_op_e_IPP_OP_GET_NOTIFICATIONS,
    ipp_op_e_IPP_OP_GET_OUTPUT_DEVICE_ATTRIBUTES, ipp_op_e_IPP_OP_GET_PRINTERS,
    ipp_op_e_IPP_OP_GET_PRINTER_ATTRIBUTES, ipp_op_e_IPP_OP_GET_PRINTER_SUPPORTED_VALUES,
    ipp_op_e_IPP_OP_GET_PRINT_SUPPORT_FILES, ipp_op_e_IPP_OP_GET_RESOURCES,
    ipp_op_e_IPP_OP_GET_RESOURCE_ATTRIBUTES, ipp_op_e_IPP_OP_GET_RESOURCE_DATA,
    ipp_op_e_IPP_OP_GET_SUBSCRIPTIONS, ipp_op_e_IPP_OP_GET_SUBSCRIPTION_ATTRIBUTES,
    ipp_op_e_IPP_OP_GET_SYSTEM_ATTRIBUTES, ipp_op_e_IPP_OP_GET_SYSTEM_SUPPORTED_VALUES,
    ipp_op_e_IPP_OP_HOLD_JOB, ipp_op_e_IPP_OP_HOLD_NEW_JOBS, ipp_op_e_IPP_OP_IDENTIFY_PRINTER,
    ipp_op_e_IPP_OP_INSTALL_RESOURCE, ipp_op_e_IPP_OP_PAUSE_ALL_PRINTERS,
    ipp_op_e_IPP_OP_PAUSE_ALL_PRINTERS_AFTER_CURRENT_JOB, ipp_op_e_IPP_OP_PAUSE_PRINTER,
    ipp_op_e_IPP_OP_PAUSE_PRINTER_AFTER_CURRENT_JOB, ipp_op_e_IPP_OP_PRINT_JOB,
    ipp_op_e_IPP_OP_PRINT_URI, ipp_op_e_IPP_OP_PRIVATE, ipp_op_e_IPP_OP_PROMOTE_JOB,
    ipp_op_e_IPP_OP_PURGE_JOBS, ipp_op_e_IPP_OP_REGISTER_OUTPUT_DEVICE,
    ipp_op_e_IPP_OP_RELEASE_HELD_NEW_JOBS, ipp_op_e_IPP_OP_RELEASE_JOB,
    ipp_op_e_IPP_OP_RENEW_SUBSCRIPTION, ipp_op_e_IPP_OP_REPROCESS_JOB, ipp_op_e_IPP_OP_RESTART_JOB,
    ipp_op_e_IPP_OP_RESTART_PRINTER, ipp_op_e_IPP_OP_RESTART_SYSTEM, ipp_op_e_IPP_OP_RESUBMIT_JOB,
    ipp_op_e_IPP_OP_RESUME_ALL_PRINTERS, ipp_op_e_IPP_OP_RESUME_JOB,
    ipp_op_e_IPP_OP_RESUME_PRINTER, ipp_op_e_IPP_OP_SCHEDULE_JOB_AFTER,
    ipp_op_e_IPP_OP_SEND_DOCUMENT, ipp_op_e_IPP_OP_SEND_NOTIFICATIONS,
    ipp_op_e_IPP_OP_SEND_RESOURCE_DATA, ipp_op_e_IPP_OP_SEND_URI,
    ipp_op_e_IPP_OP_SET_DOCUMENT_ATTRIBUTES, ipp_op_e_IPP_OP_SET_JOB_ATTRIBUTES,
    ipp_op_e_IPP_OP_SET_PRINTER_ATTRIBUTES, ipp_op_e_IPP_OP_SET_RESOURCE_ATTRIBUTES,
    ipp_op_e_IPP_OP_SET_SYSTEM_ATTRIBUTES, ipp_op_e_IPP_OP_SHUTDOWN_ALL_PRINTERS,
    ipp_op_e_IPP_OP_SHUTDOWN_ONE_PRINTER, ipp_op_e_IPP_OP_SHUTDOWN_PRINTER,
    ipp_op_e_IPP_OP_STARTUP_ALL_PRINTERS, ipp_op_e_IPP_OP_STARTUP_ONE_PRINTER,
    ipp_op_e_IPP_OP_STARTUP_PRINTER, ipp_op_e_IPP_OP_SUSPEND_CURRENT_JOB,
    ipp_op_e_IPP_OP_UPDATE_ACTIVE_JOBS, ipp_op_e_IPP_OP_UPDATE_DOCUMENT_STATUS,
    ipp_op_e_IPP_OP_UPDATE_JOB_STATUS, ipp_op_e_IPP_OP_UPDATE_OUTPUT_DEVICE_ATTRIBUTES,
    ipp_op_e_IPP_OP_VALIDATE_DOCUMENT, ipp_op_e_IPP_OP_VALIDATE_JOB, ipp_op_t, ipp_orient_e,
    ipp_orient_e_IPP_ORIENT_LANDSCAPE, ipp_orient_e_IPP_ORIENT_NONE,
    ipp_orient_e_IPP_ORIENT_PORTRAIT, ipp_orient_e_IPP_ORIENT_REVERSE_LANDSCAPE,
    ipp_orient_e_IPP_ORIENT_REVERSE_PORTRAIT, ipp_orient_t, ipp_pstate_e,
    ipp_pstate_e_IPP_PSTATE_IDLE, ipp_pstate_e_IPP_PSTATE_PROCESSING,
    ipp_pstate_e_IPP_PSTATE_STOPPED, ipp_pstate_t, ipp_quality_e, ipp_quality_e_IPP_QUALITY_DRAFT,
    ipp_quality_e_IPP_QUALITY_HIGH, ipp_quality_e_IPP_QUALITY_NORMAL, ipp_quality_t, ipp_res_e,
    ipp_res_e_IPP_RES_PER_CM, ipp_res_e_IPP_RES_PER_INCH, ipp_res_t, ipp_rstate_e,
    ipp_rstate_e_IPP_RSTATE_ABORTED, ipp_rstate_e_IPP_RSTATE_AVAILABLE,
    ipp_rstate_e_IPP_RSTATE_CANCELED, ipp_rstate_e_IPP_RSTATE_INSTALLED,
    ipp_rstate_e_IPP_RSTATE_PENDING, ipp_rstate_t, ipp_sstate_e, ipp_sstate_e_IPP_SSTATE_IDLE,
    ipp_sstate_e_IPP_SSTATE_PROCESSING, ipp_sstate_e_IPP_SSTATE_STOPPED, ipp_sstate_t, ipp_state_e,
    ipp_state_e_IPP_STATE_ATTRIBUTE, ipp_state_e_IPP_STATE_DATA, ipp_state_e_IPP_STATE_ERROR,
    ipp_state_e_IPP_STATE_HEADER, ipp_state_e_IPP_STATE_IDLE, ipp_state_t, ipp_status_e,
    ipp_status_e_IPP_STATUS_CUPS_INVALID, ipp_status_e_IPP_STATUS_CUPS_SEE_OTHER,
    ipp_status_e_IPP_STATUS_ERROR_ACCOUNT_AUTHORIZATION_FAILED,
    ipp_status_e_IPP_STATUS_ERROR_ACCOUNT_CLOSED,
    ipp_status_e_IPP_STATUS_ERROR_ACCOUNT_INFO_NEEDED,
    ipp_status_e_IPP_STATUS_ERROR_ACCOUNT_LIMIT_REACHED,
    ipp_status_e_IPP_STATUS_ERROR_ATTRIBUTES_NOT_SETTABLE,
    ipp_status_e_IPP_STATUS_ERROR_ATTRIBUTES_OR_VALUES, ipp_status_e_IPP_STATUS_ERROR_BAD_REQUEST,
    ipp_status_e_IPP_STATUS_ERROR_BUSY, ipp_status_e_IPP_STATUS_ERROR_CHARSET,
    ipp_status_e_IPP_STATUS_ERROR_COMPRESSION_ERROR,
    ipp_status_e_IPP_STATUS_ERROR_COMPRESSION_NOT_SUPPORTED,
    ipp_status_e_IPP_STATUS_ERROR_CONFLICTING,
    ipp_status_e_IPP_STATUS_ERROR_CUPS_ACCOUNT_AUTHORIZATION_FAILED,
    ipp_status_e_IPP_STATUS_ERROR_CUPS_ACCOUNT_CLOSED,
    ipp_status_e_IPP_STATUS_ERROR_CUPS_ACCOUNT_INFO_NEEDED,
    ipp_status_e_IPP_STATUS_ERROR_CUPS_ACCOUNT_LIMIT_REACHED,
    ipp_status_e_IPP_STATUS_ERROR_CUPS_AUTHENTICATION_CANCELED,
    ipp_status_e_IPP_STATUS_ERROR_CUPS_PKI, ipp_status_e_IPP_STATUS_ERROR_CUPS_UPGRADE_REQUIRED,
    ipp_status_e_IPP_STATUS_ERROR_DEVICE, ipp_status_e_IPP_STATUS_ERROR_DOCUMENT_ACCESS,
    ipp_status_e_IPP_STATUS_ERROR_DOCUMENT_FORMAT_ERROR,
    ipp_status_e_IPP_STATUS_ERROR_DOCUMENT_FORMAT_NOT_SUPPORTED,
    ipp_status_e_IPP_STATUS_ERROR_DOCUMENT_PASSWORD,
    ipp_status_e_IPP_STATUS_ERROR_DOCUMENT_PERMISSION,
    ipp_status_e_IPP_STATUS_ERROR_DOCUMENT_SECURITY,
    ipp_status_e_IPP_STATUS_ERROR_DOCUMENT_UNPRINTABLE, ipp_status_e_IPP_STATUS_ERROR_FORBIDDEN,
    ipp_status_e_IPP_STATUS_ERROR_GONE, ipp_status_e_IPP_STATUS_ERROR_IGNORED_ALL_NOTIFICATIONS,
    ipp_status_e_IPP_STATUS_ERROR_IGNORED_ALL_SUBSCRIPTIONS,
    ipp_status_e_IPP_STATUS_ERROR_INTERNAL, ipp_status_e_IPP_STATUS_ERROR_JOB_CANCELED,
    ipp_status_e_IPP_STATUS_ERROR_MULTIPLE_JOBS_NOT_SUPPORTED,
    ipp_status_e_IPP_STATUS_ERROR_NOT_ACCEPTING_JOBS,
    ipp_status_e_IPP_STATUS_ERROR_NOT_AUTHENTICATED, ipp_status_e_IPP_STATUS_ERROR_NOT_AUTHORIZED,
    ipp_status_e_IPP_STATUS_ERROR_NOT_FETCHABLE, ipp_status_e_IPP_STATUS_ERROR_NOT_FOUND,
    ipp_status_e_IPP_STATUS_ERROR_NOT_POSSIBLE,
    ipp_status_e_IPP_STATUS_ERROR_OPERATION_NOT_SUPPORTED,
    ipp_status_e_IPP_STATUS_ERROR_PRINTER_IS_DEACTIVATED,
    ipp_status_e_IPP_STATUS_ERROR_PRINT_SUPPORT_FILE_NOT_FOUND,
    ipp_status_e_IPP_STATUS_ERROR_REQUEST_ENTITY, ipp_status_e_IPP_STATUS_ERROR_REQUEST_VALUE,
    ipp_status_e_IPP_STATUS_ERROR_SERVICE_UNAVAILABLE, ipp_status_e_IPP_STATUS_ERROR_TEMPORARY,
    ipp_status_e_IPP_STATUS_ERROR_TIMEOUT, ipp_status_e_IPP_STATUS_ERROR_TOO_MANY_DOCUMENTS,
    ipp_status_e_IPP_STATUS_ERROR_TOO_MANY_JOBS,
    ipp_status_e_IPP_STATUS_ERROR_TOO_MANY_SUBSCRIPTIONS, ipp_status_e_IPP_STATUS_ERROR_URI_SCHEME,
    ipp_status_e_IPP_STATUS_ERROR_VERSION_NOT_SUPPORTED, ipp_status_e_IPP_STATUS_OK,
    ipp_status_e_IPP_STATUS_OK_BUT_CANCEL_SUBSCRIPTION, ipp_status_e_IPP_STATUS_OK_CONFLICTING,
    ipp_status_e_IPP_STATUS_OK_EVENTS_COMPLETE, ipp_status_e_IPP_STATUS_OK_IGNORED_NOTIFICATIONS,
    ipp_status_e_IPP_STATUS_OK_IGNORED_OR_SUBSTITUTED,
    ipp_status_e_IPP_STATUS_OK_IGNORED_SUBSCRIPTIONS, ipp_status_e_IPP_STATUS_OK_TOO_MANY_EVENTS,
    ipp_status_e_IPP_STATUS_REDIRECTION_OTHER_SITE, ipp_status_t, ipp_t, ipp_tag_e,
    ipp_tag_e_IPP_TAG_ADMINDEFINE, ipp_tag_e_IPP_TAG_BEGIN_COLLECTION, ipp_tag_e_IPP_TAG_BOOLEAN,
    ipp_tag_e_IPP_TAG_CHARSET, ipp_tag_e_IPP_TAG_CUPS_CONST, ipp_tag_e_IPP_TAG_CUPS_INVALID,
    ipp_tag_e_IPP_TAG_CUPS_MASK, ipp_tag_e_IPP_TAG_DATE, ipp_tag_e_IPP_TAG_DEFAULT,
    ipp_tag_e_IPP_TAG_DELETEATTR, ipp_tag_e_IPP_TAG_DOCUMENT, ipp_tag_e_IPP_TAG_END,
    ipp_tag_e_IPP_TAG_END_COLLECTION, ipp_tag_e_IPP_TAG_ENUM, ipp_tag_e_IPP_TAG_EVENT_NOTIFICATION,
    ipp_tag_e_IPP_TAG_EXTENSION, ipp_tag_e_IPP_TAG_INTEGER, ipp_tag_e_IPP_TAG_JOB,
    ipp_tag_e_IPP_TAG_KEYWORD, ipp_tag_e_IPP_TAG_LANGUAGE, ipp_tag_e_IPP_TAG_MEMBERNAME,
    ipp_tag_e_IPP_TAG_MIMETYPE, ipp_tag_e_IPP_TAG_NAME, ipp_tag_e_IPP_TAG_NAMELANG,
    ipp_tag_e_IPP_TAG_NOTSETTABLE, ipp_tag_e_IPP_TAG_NOVALUE, ipp_tag_e_IPP_TAG_OPERATION,
    ipp_tag_e_IPP_TAG_PRINTER, ipp_tag_e_IPP_TAG_RANGE, ipp_tag_e_IPP_TAG_RESERVED_STRING,
    ipp_tag_e_IPP_TAG_RESOLUTION, ipp_tag_e_IPP_TAG_RESOURCE, ipp_tag_e_IPP_TAG_STRING,
    ipp_tag_e_IPP_TAG_SUBSCRIPTION, ipp_tag_e_IPP_TAG_SYSTEM, ipp_tag_e_IPP_TAG_TEXT,
    ipp_tag_e_IPP_TAG_TEXTLANG, ipp_tag_e_IPP_TAG_UNKNOWN, ipp_tag_e_IPP_TAG_UNSUPPORTED_GROUP,
    ipp_tag_e_IPP_TAG_UNSUPPORTED_VALUE, ipp_tag_e_IPP_TAG_URI, ipp_tag_e_IPP_TAG_URISCHEME,
    ipp_tag_e_IPP_TAG_ZERO, ipp_tag_t, ipp_uchar_t, CUPS_BC_FD, CUPS_DEST_FLAGS_CANCELED,
    CUPS_DEST_FLAGS_CONNECTING, CUPS_DEST_FLAGS_DEVICE, CUPS_DEST_FLAGS_ERROR,
    CUPS_DEST_FLAGS_MORE, CUPS_DEST_FLAGS_NONE, CUPS_DEST_FLAGS_REMOVED, CUPS_DEST_FLAGS_RESOLVING,
    CUPS_DEST_FLAGS_UNCONNECTED, CUPS_JOBID_ALL, CUPS_JOBID_CURRENT, CUPS_MEDIA_FLAGS_BORDERLESS,
    CUPS_MEDIA_FLAGS_DEFAULT, CUPS_MEDIA_FLAGS_DUPLEX, CUPS_MEDIA_FLAGS_EXACT,
    CUPS_MEDIA_FLAGS_READY, CUPS_TIMEOUT_DEFAULT, CUPS_VERSION_MAJOR, CUPS_VERSION_MINOR,
    CUPS_VERSION_PATCH, CUPS_WHICHJOBS_ACTIVE, CUPS_WHICHJOBS_ALL, CUPS_WHICHJOBS_COMPLETED,
};

mod patches;
pub use patches::*;
