[package]
name = "libcups"
version = "1.0.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
libcups-sys = { version = "2.4.0", path = "../libcups-sys" }
log = "0.4.20"
serde = { version = "1.0.197", features = ["derive"] }
