[package]
name = "simple-sane"
version = "1.0.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
bitflags = "2.4.2"
bstr = "1.9.0"
log = "0.4.20"
thiserror = "1.0.56"

[build-dependencies]
bindgen = "0.69.2"
